name: MSBuild
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: windows-latest
    name: "${{ matrix.msvc_version }}"
    strategy:
      matrix:
        msvc_version: ['15.0', '16.0', '17.0'] # vs2017, vs2019, vs2022
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2 # updated on Jan 16
      
      - uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2
        with:
          vs-version: ${{ matrix.msvc_version }}

      - run: msbuild msvc.sln /m
        shell: cmd